This broke building SimpleAgenda for me:
In file included from SoundBackend.m:1:
/usr/local/include/AppKit/NSSound.h:57:1: error: unknown type name 'APPKIT_EXPORT_CLASS'
APPKIT_EXPORT_CLASS